services:
  # A Docker web service
  - type: web
    name: uptime-kuma
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    branch: master # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
